import type { CommunityPost, ContactMethodId, ContactPreferences, Resource, User } from '@/types';

export const CURRENT_USER_ID = 'u_guest';

export const USERS: User[] = [
  {
    id: 'u_guest',
    name: 'Guest Student',
    initials: 'GS',
    emoji: '🎓',
    bio: 'You\u2019re browsing as a guest. Sign in to personalize your profile and track your activity.',
    department: 'Not signed in · Demo account',
    color: 'bg-gradient-to-br from-brand-400 to-violet-500',
  },
  {
    id: 'u_aisha',
    name: 'Aisha',
    initials: 'AS',
    emoji: '🌸',
    bio: 'Computer Science student | DSA enthusiast | Always happy to help',
    department: 'CSE · 3rd Year',
    color: 'bg-gradient-to-br from-brand-400 to-violet-500',
  },
  {
    id: 'u_rohan',
    name: 'Rohan Verma',
    initials: 'RV',
    emoji: '🚀',
    bio: 'ECE student · Hardware tinkerer · Hackathon regular',
    department: 'ECE · 2nd Year',
    color: 'bg-gradient-to-br from-sky-400 to-violet-500',
  },
  {
    id: 'u_meera',
    name: 'Meera Iyer',
    initials: 'MI',
    emoji: '✨',
    bio: 'IT student | Event coordinator | Loves a good giveaway',
    department: 'IT · 3rd Year',
    color: 'bg-gradient-to-br from-amber-400 to-brand-500',
  },
  {
    id: 'u_kabir',
    name: 'Kabir Naidu',
    initials: 'KN',
    emoji: '🎯',
    bio: 'Mechanical engg · Notes hoarder · Always lending something',
    department: 'MECH · 4th Year',
    color: 'bg-gradient-to-br from-emerald-400 to-sky-500',
  },
];

export const USER_MAP: Record<string, User> = USERS.reduce(
  (acc, u) => ({ ...acc, [u.id]: u }),
  {} as Record<string, User>,
);

export const DEFAULT_CONTACT_PREFERENCES: ContactPreferences = {
  whatsapp: false,
  instagram: false,
  email: false,
};

export interface DemoContactDetail {
  id: ContactMethodId;
  label: string;
  display: string;
  href: string;
}

/** Fake handles only — never real personal contact info. */
export const DEMO_CONTACT_DETAILS: Record<string, Record<ContactMethodId, DemoContactDetail>> = {
  [CURRENT_USER_ID]: {
    whatsapp: {
      id: 'whatsapp',
      label: 'WhatsApp',
      display: '+91 90000 00000 (demo)',
      href: 'https://wa.me/919000000000',
    },
    instagram: {
      id: 'instagram',
      label: 'Instagram',
      display: '@rexchange.guest (demo)',
      href: 'https://www.instagram.com/rexchange.guest',
    },
    email: {
      id: 'email',
      label: 'Email',
      display: 'guest.student@srm-demo.example',
      href: 'mailto:guest.student@srm-demo.example',
    },
  },
};

export function getSharedContactMethods(
  userId: string,
  prefs: ContactPreferences,
): DemoContactDetail[] {
  const details = DEMO_CONTACT_DETAILS[userId];
  if (!details) return [];
  return (['whatsapp', 'instagram', 'email'] as const).filter((id) => prefs[id]).map((id) => details[id]);
}

const now = Date.now();
const hour = 3600_000;
const day = 24 * hour;

export const SEED_RESOURCES: Resource[] = [
  {
    id: 'r_dsa_notes',
    title: 'DSA Notes 2024 (Complete)',
    description: 'Handwritten + typed notes covering arrays, trees, graphs, DP, and greedy. Clean and easy to follow.',
    category: 'books',
    availability: 'online',
    condition: 'Digital — PDF, 86 pages',
    image: 'https://images.pexels.com/photos/7054499/pexels-photo-7054499.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'Online / SRM Campus',
    contributorId: 'u_aisha',
    sharedToCommunity: true,
    createdAt: now - 2 * day,
  },
  {
    id: 'r_usbc_cable',
    title: 'USB-C to USB-C Cable',
    description: 'Braided USB-C to USB-C cable, fast charging + data transfer. Works perfectly, just upgraded to a longer one.',
    category: 'electronics',
    availability: 'lending',
    condition: 'Good — barely used',
    image: 'https://images.pexels.com/photos/3921630/pexels-photo-3921630.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'SRM Campus, Tech Park',
    contributorId: 'u_rohan',
    sharedToCommunity: false,
    createdAt: now - 5 * hour,
  },
  {
    id: 'r_ds_textbook',
    title: 'Data Structures Textbook (Cormen)',
    description: 'Introduction to Algorithms, 3rd edition. Slightly worn cover, all pages intact. Great for DSA prep.',
    category: 'books',
    availability: 'sale',
    price: 350,
    condition: 'Good — minor cover wear',
    image: 'https://images.pexels.com/photos/4778412/pexels-photo-4778412.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'SRM Main Library',
    contributorId: 'u_kabir',
    sharedToCommunity: false,
    createdAt: now - 3 * day,
  },
  {
    id: 'r_java_notes',
    title: 'Java Programming Notes',
    description: 'Sem 3 Java notes covering OOP, collections, exceptions, and JDBC. Includes 2 sample project walkthroughs.',
    category: 'books',
    availability: 'free',
    condition: 'Digital — PDF + 3 code samples',
    image: 'https://images.pexels.com/photos/6958526/pexels-photo-6958526.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'Online',
    contributorId: 'u_aisha',
    sharedToCommunity: true,
    createdAt: now - 1 * day,
  },
  {
    id: 'r_dsa_papers',
    title: 'Previous Year DSA Question Papers',
    description: 'Last 4 years of DSA mid-sem and end-sem papers with answer keys for the tricky ones. Lifesaver before exams.',
    category: 'books',
    availability: 'online',
    condition: 'Digital — PDF bundle',
    image: 'https://images.pexels.com/photos/167682/pexels-photo-167682.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'Online',
    contributorId: 'u_kabir',
    sharedToCommunity: false,
    createdAt: now - 4 * day,
  },
  {
    id: 'r_fest_ticket',
    title: 'Campus Fest 2026 — 2 Day Pass',
    description: 'Transferable 2-day pass for the annual campus fest. Can\'t attend due to an internship interview clash.',
    category: 'events',
    availability: 'sale',
    price: 500,
    condition: 'Digital pass — transferable',
    image: 'https://images.pexels.com/photos/4218027/pexels-photo-4218027.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'SRM Auditorium',
    contributorId: 'u_meera',
    sharedToCommunity: true,
    createdAt: now - 6 * hour,
  },
  {
    id: 'r_calculator',
    title: 'Scientific Calculator (Casio fx-991)',
    description: 'Casio fx-991EX ClassWiz. Perfect for exams. Light scratches on the back, works flawlessly.',
    category: 'electronics',
    availability: 'rent',
    price: 30,
    condition: 'Good — light cosmetic scratches',
    image: 'https://images.pexels.com/photos/6368841/pexels-photo-6368841.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'SRM Campus, Main Block',
    contributorId: 'u_kabir',
    sharedToCommunity: false,
    createdAt: now - 2 * day,
  },
  {
    id: 'r_laptop_stand',
    title: 'Aluminium Laptop Stand',
    description: 'Foldable aluminium stand, elevates laptop for better posture. Graduating, don\'t need it anymore.',
    category: 'electronics',
    availability: 'free',
    condition: 'Like new',
    image: 'https://images.pexels.com/photos/6045231/pexels-photo-6045231.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'SRM Hostel Block C',
    contributorId: 'u_meera',
    sharedToCommunity: true,
    createdAt: now - 8 * hour,
  },
  {
    id: 'r_dbms_notes',
    title: 'DBMS Notes + ER Diagrams',
    description: 'Full DBMS notes: normalization, transactions, SQL cheatsheet, and 6 ER diagram examples.',
    category: 'books',
    availability: 'online',
    condition: 'Digital — PDF, 52 pages',
    image: 'https://images.pexels.com/photos/6929270/pexels-photo-6929270.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'Online',
    contributorId: 'u_aisha',
    sharedToCommunity: false,
    createdAt: now - 5 * day,
  },
  {
    id: 'r_engg_math',
    title: 'Engineering Mathematics Textbook (B.S. Grewal)',
    description: 'B.S. Grewal, 44th edition. Covers Calc, Linear Algebra, ODE, PDE. Some pencil annotations inside.',
    category: 'books',
    availability: 'sale',
    price: 250,
    condition: 'Fair — pencil notes inside',
    image: 'https://images.pexels.com/photos/479817/pexels-photo-479817.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'SRM Campus, Tech Park',
    contributorId: 'u_kabir',
    sharedToCommunity: false,
    createdAt: now - 6 * day,
  },
  {
    id: 'r_hdmi_cable',
    title: 'HDMI Cable (2m)',
    description: 'Standard 2m HDMI cable for presentations / monitor hookup. Lending it out, bring it back in a day.',
    category: 'electronics',
    availability: 'lending',
    condition: 'Good',
    image: 'https://images.pexels.com/photos/3921710/pexels-photo-3921710.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'SRM Campus, Innovation Lab',
    contributorId: 'u_rohan',
    sharedToCommunity: false,
    createdAt: now - 10 * hour,
  },
  {
    id: 'r_stationery',
    title: 'Extra Stationery Kit',
    description: 'Pens, highlighters, sticky notes, a geometry box — moving out and don\'t want to carry it all.',
    category: 'giveaway',
    availability: 'free',
    condition: 'Good — assorted',
    image: 'https://images.pexels.com/photos/6368836/pexels-photo-6368836.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'SRM Hostel Block A',
    contributorId: 'u_meera',
    sharedToCommunity: true,
    createdAt: now - 12 * hour,
  },
  {
    id: 'r_sem1_math_papers',
    title: 'Sem 1 Mathematics Question Papers',
    description: 'Previous-year Sem 1 Mathematics-I question papers (3 sets) with worked solutions for calculus and linear algebra sections.',
    category: 'books',
    availability: 'online',
    condition: 'Digital — PDF bundle, 3 sets',
    image: 'https://images.pexels.com/photos/167682/pexels-photo-167682.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'Online',
    contributorId: 'u_aisha',
    sharedToCommunity: false,
    createdAt: now - 7 * day,
  },
  {
    id: 'r_sem1_math_guide',
    title: 'Sem 1 Mathematics Study Guide',
    description: 'Complete study guide for Mathematics-I: limits, continuity, differentiation, matrices, and eigenvalues. Includes formula sheet and 20 solved examples.',
    category: 'books',
    availability: 'free',
    condition: 'Digital — PDF, 64 pages',
    image: 'https://images.pexels.com/photos/6929270/pexels-photo-6929270.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'Online',
    contributorId: 'u_aisha',
    sharedToCommunity: true,
    createdAt: now - 7 * day - 2 * hour,
  },
  {
    id: 'r_sem1_coding_sheets',
    title: 'Sem 1 Programming Practice Sheets',
    description: 'C programming practice sheets covering variables, loops, arrays, functions, and basic recursion. 50 problems with difficulty tags.',
    category: 'books',
    availability: 'online',
    condition: 'Digital — PDF + code stubs',
    image: 'https://images.pexels.com/photos/6958526/pexels-photo-6958526.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'Online',
    contributorId: 'u_kabir',
    sharedToCommunity: false,
    createdAt: now - 8 * day,
  },
  {
    id: 'r_sem1_papers',
    title: 'Sem 1 Previous-Year Question Papers (All Subjects)',
    description: 'Bundle of Sem 1 PYQs across Physics, Chemistry, Math, English, and Programming. 2 years of mid-sem + end-sem papers.',
    category: 'books',
    availability: 'online',
    condition: 'Digital — PDF bundle',
    image: 'https://images.pexels.com/photos/7054499/pexels-photo-7054499.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'Online',
    contributorId: 'u_kabir',
    sharedToCommunity: true,
    createdAt: now - 8 * day - 4 * hour,
  },
  {
    id: 'r_sem1_notes',
    title: 'Sem 1 Subject Notes Bundle',
    description: 'Handwritten notes for Engineering Physics, Chemistry, and Maths-I. Clean diagrams and key formulas highlighted.',
    category: 'books',
    availability: 'free',
    condition: 'Digital — scanned PDF, 120 pages',
    image: 'https://images.pexels.com/photos/479817/pexels-photo-479817.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'Online',
    contributorId: 'u_aisha',
    sharedToCommunity: false,
    createdAt: now - 9 * day,
  },
  {
    id: 'r_sem2_math_papers',
    title: 'Sem 2 Mathematics Question Papers',
    description: 'Previous-year Sem 2 Mathematics-II papers covering vector calculus, Laplace transforms, and probability. 3 sets with solutions.',
    category: 'books',
    availability: 'online',
    condition: 'Digital — PDF bundle',
    image: 'https://images.pexels.com/photos/167682/pexels-photo-167682.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'Online',
    contributorId: 'u_kabir',
    sharedToCommunity: false,
    createdAt: now - 10 * day,
  },
  {
    id: 'r_sem2_coding_sheets',
    title: 'Sem 2 Coding & Programming Sheets',
    description: 'OOP in C++ practice sheets: classes, inheritance, polymorphism, templates, and STL. 40 graded problems with sample solutions.',
    category: 'books',
    availability: 'online',
    condition: 'Digital — PDF + .cpp files',
    image: 'https://images.pexels.com/photos/6958526/pexels-photo-6958526.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'Online',
    contributorId: 'u_aisha',
    sharedToCommunity: true,
    createdAt: now - 10 * day - 3 * hour,
  },
  {
    id: 'r_sem2_papers',
    title: 'Sem 2 Previous-Year Question Papers',
    description: 'Sem 2 PYQs for Maths-II, OOP, Basic Electrical, and Environmental Science. 2 years of papers, no answer keys.',
    category: 'books',
    availability: 'free',
    condition: 'Digital — PDF bundle',
    image: 'https://images.pexels.com/photos/7054499/pexels-photo-7054499.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'Online',
    contributorId: 'u_kabir',
    sharedToCommunity: false,
    createdAt: now - 11 * day,
  },
  {
    id: 'r_sem2_subject_guide',
    title: 'Sem 2 Subject Guides (OOP + Maths-II)',
    description: 'Compact revision guides for Object-Oriented Programming and Mathematics-II. Key concepts, formulas, and quick-reference tables.',
    category: 'books',
    availability: 'online',
    condition: 'Digital — PDF, 48 pages',
    image: 'https://images.pexels.com/photos/6929270/pexels-photo-6929270.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'Online',
    contributorId: 'u_aisha',
    sharedToCommunity: false,
    createdAt: now - 11 * day - 6 * hour,
  },
  {
    id: 'r_prog_practice',
    title: 'Programming Practice Sheets (DSA Focused)',
    description: '100 DSA practice problems sorted by topic: arrays, strings, linked lists, stacks, queues, trees, and graphs. Difficulty-rated with hints.',
    category: 'books',
    availability: 'online',
    condition: 'Digital — PDF + starter code',
    image: 'https://images.pexels.com/photos/6958526/pexels-photo-6958526.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'Online',
    contributorId: 'u_kabir',
    sharedToCommunity: true,
    createdAt: now - 12 * day,
  },
  {
    id: 'r_lab_prep',
    title: 'Lab Preparation Material (OOP + DS Lab)',
    description: 'Viva questions, expected lab programs, and observation templates for OOP and Data Structures labs. Covers the most-asked experiments.',
    category: 'books',
    availability: 'free',
    condition: 'Digital — PDF, 30 pages',
    image: 'https://images.pexels.com/photos/6929270/pexels-photo-6929270.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'Online',
    contributorId: 'u_aisha',
    sharedToCommunity: false,
    createdAt: now - 12 * day - 5 * hour,
  },
  {
    id: 'r_univ_papers',
    title: 'Previous-Year University Question Papers (Multi-Subject)',
    description: 'University-level PYQs across CSE, ECE, and IT for semesters 1-4. Includes Maths, Physics, Programming, and core subjects.',
    category: 'books',
    availability: 'online',
    condition: 'Digital — large PDF bundle',
    image: 'https://images.pexels.com/photos/4778412/pexels-photo-4778412.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'Online',
    contributorId: 'u_kabir',
    sharedToCommunity: false,
    createdAt: now - 13 * day,
  },
  {
    id: 'r_revision_notes',
    title: 'Subject-Wise Revision Notes (CSE Sem 3)',
    description: 'Concise revision notes for DSA, DBMS, OOP, and Digital Logic. Bullet-point format, ideal for last-minute revision before exams.',
    category: 'books',
    availability: 'free',
    condition: 'Digital — PDF, 72 pages',
    image: 'https://images.pexels.com/photos/7054499/pexels-photo-7054499.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    location: 'Online',
    contributorId: 'u_aisha',
    sharedToCommunity: true,
    createdAt: now - 13 * day - 8 * hour,
  },
];

export const SEED_POSTS: CommunityPost[] = [
  {
    id: 'p_usbc_urgent',
    type: 'urgent',
    text: 'My USB-C cable stopped working before my hackathon. Can anyone lend me one for a few hours?',
    need: 'USB-C data-transfer cable',
    why: 'My cable stopped working before my hackathon starts in 2 hours. I just need to flash a device.',
    category: 'electronics',
    urgency: 'asap',
    location: 'SRM Campus, Innovation Lab',
    authorId: 'u_rohan',
    comments: [
      { id: 'c1', authorId: 'u_aisha', text: 'I have one! Bringing it to the lab now.', createdAt: now - 20 * 60_000 },
    ],
    helpOffers: [],
    createdAt: now - 35 * 60_000,
  },
  {
    id: 'p_calc_urgent',
    type: 'urgent',
    text: 'Forgot my scientific calculator and my math exam is tomorrow morning. Does anyone have one I can borrow overnight?',
    need: 'Scientific calculator (any model)',
    why: 'Left mine at home and the exam hall won\'t provide one. Exam is 9 AM tomorrow.',
    category: 'electronics',
    urgency: 'today',
    location: 'SRM Campus, Main Block',
    authorId: 'u_meera',
    comments: [],
    helpOffers: [
      { id: 'h1', authorId: 'u_kabir', message: 'I have the Casio fx-991 listed — it\'s yours overnight.', createdAt: now - 90 * 60_000 },
    ],
    createdAt: now - 2 * hour,
  },
  {
    id: 'p_dsa_urgent',
    type: 'urgent',
    text: 'Urgently need previous year DSA question papers. Mid-sem in 3 days and I have nothing to practice from!',
    need: 'Previous year DSA question papers',
    why: 'Mid-sem in 3 days and I completely forgot to collect papers. Need them for last-minute practice.',
    category: 'books',
    urgency: 'week',
    location: 'SRM Campus',
    authorId: 'u_aisha',
    comments: [
      { id: 'c2', authorId: 'u_kabir', text: 'Check the resource listing — I uploaded 4 years of papers!', createdAt: now - 5 * hour },
    ],
    helpOffers: [],
    createdAt: now - 6 * hour,
  },
  {
    id: 'p_dsa_discuss',
    type: 'discussion',
    text: 'Does anyone have previous-year DSA question papers? The library copies are all issued out 😭',
    authorId: 'u_aisha',
    comments: [
      { id: 'c3', authorId: 'u_kabir', text: 'I just uploaded a bundle — check Electronics & Study material on the dashboard.', createdAt: now - 1 * day },
      { id: 'c4', authorId: 'u_meera', text: 'Same here, needed them last sem too. Kabir saves lives fr.', createdAt: now - 22 * hour },
    ],
    helpOffers: [],
    createdAt: now - 1 * day - 2 * hour,
  },
  {
    id: 'p_java_discuss',
    type: 'discussion',
    text: 'Can someone recommend a good Java resource for JDBC and servlets? The slides aren\'t clicking for me.',
    authorId: 'u_meera',
    comments: [
      { id: 'c5', authorId: 'u_aisha', text: 'I shared my Java notes in the feed — has a full JDBC walkthrough + sample project.', createdAt: now - 1 * day },
    ],
    helpOffers: [],
    createdAt: now - 1 * day - 5 * hour,
  },
  {
    id: 'p_stand_giveaway',
    type: 'discussion',
    text: 'Giving away my aluminium laptop stand! Graduating and it won\'t fit in my suitcase. First come first serve 🎁',
    resourceLink: 'r_laptop_stand',
    authorId: 'u_meera',
    comments: [
      { id: 'c6', authorId: 'u_rohan', text: 'Mine! Picking it up from Block C this evening.', createdAt: now - 7 * hour },
    ],
    helpOffers: [],
    createdAt: now - 9 * hour,
  },
  {
    id: 'p_fest_discuss',
    type: 'discussion',
    text: 'Who all are going to Campus Fest 2026? I have an extra 2-day pass to sell if anyone needs one 🎶',
    resourceLink: 'r_fest_ticket',
    authorId: 'u_meera',
    comments: [
      { id: 'c7', authorId: 'u_aisha', text: 'Wait how much? A few of us from CSE were looking!', createdAt: now - 4 * hour },
    ],
    helpOffers: [],
    createdAt: now - 4 * hour,
  },
];

export const SAMPLE_IMAGES = [
  { label: 'Books & Notes', url: 'https://images.pexels.com/photos/7054499/pexels-photo-7054499.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { label: 'Cables & Electronics', url: 'https://images.pexels.com/photos/3921630/pexels-photo-3921630.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { label: 'Concert & Events', url: 'https://images.pexels.com/photos/4218027/pexels-photo-4218027.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { label: 'Calculator & Stationery', url: 'https://images.pexels.com/photos/6368841/pexels-photo-6368841.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { label: 'Laptop & Desk', url: 'https://images.pexels.com/photos/6045231/pexels-photo-6045231.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { label: 'Textbook', url: 'https://images.pexels.com/photos/4778412/pexels-photo-4778412.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
];

export const POST_SAMPLE_IMAGES = [
  { label: 'Study desk', url: 'https://images.pexels.com/photos/7054499/pexels-photo-7054499.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { label: 'Notes & books', url: 'https://images.pexels.com/photos/6929270/pexels-photo-6929270.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { label: 'Electronics', url: 'https://images.pexels.com/photos/3921630/pexels-photo-3921630.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { label: 'Event / concert', url: 'https://images.pexels.com/photos/4218027/pexels-photo-4218027.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { label: 'Giveaway / stationery', url: 'https://images.pexels.com/photos/6368836/pexels-photo-6368836.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
];
